version: '3'

services:
  api:
    build: .
    ports:
      - 8080:8080
    volumes:
      - ./:/go/src/github.com/maxiatanasio/golang-todo

  mongodb:
    depends_on:
      - api
    image: mongo
    ports:
      - 27017:27017
